version: '2.2'

x-gulpbot: &gulpbot
  image: node:14-alpine
  working_dir: /repo/
  command: node /repo/scripts/gulpbot.js
  volumes: [ "../:/repo/" ]
  environment:
    ANKR_PROJECT_ID: ${ANKR_PROJECT_ID}
    ANKR_APIKEY_BSCMAIN: ${ANKR_APIKEY_BSCMAIN}
    ANKR_APIKEY_BSCTEST: ${ANKR_APIKEY_BSCTEST}
    TELEGRAM_BOT_API_KEY: ${TELEGRAM_BOT_API_KEY}
    TELEGRAM_BOT_CHAT_ID: ${TELEGRAM_BOT_CHAT_ID}
    PRIVATE_KEY: ${GULPBOT_PRIVATE_KEY}
  restart: always

services:
  gulpbot-bscmain:
    <<: *gulpbot
    container_name: gulpbot-bscmain
    command: node /repo/scripts/gulpbot.js bscmain
  gulpbot-avaxmain:
    <<: *gulpbot
    container_name: gulpbot-avaxmain
    command: node /repo/scripts/gulpbot.js avaxmain
  gulpbot-ftmmain:
    <<: *gulpbot
    container_name: gulpbot-ftmmain
    command: node /repo/scripts/gulpbot.js ftmmain
