# This workflow will do a clean install of dependencies, build the source code and run tests
name: Truffle CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
        NODE_OPTIONS: --max-old-space-size=4096
    - run: env > .env
      env:
        ANKR_PROJECT_ID: ${{ secrets.ANKR_PROJECT_ID }}
        ANKR_APIKEY_BSCMAIN: ${{ secrets.ANKR_APIKEY_BSCMAIN }}
        ANKR_APIKEY_BSCTEST: ${{ secrets.ANKR_APIKEY_BSCTEST }}
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    - run: ./scripts/start-bscmain-fork.sh & rm -rf ./build/ && npm run test:bscmain && pkill node
#    - run: ./scripts/start-bsctest-fork.sh & rm -rf ./build/ && npm run test:bsctest && pkill node
